### ISSUE TITLE
Feature Request: Select media from strapi media library 

### ISSUE THREAD

**Issue by the-unknown** [ckeditor/strapi-plugin-ckeditor#10]
Hey there,

as the title says - I would like to select media from the media library in Strapi.

Best Regards

**Comment by Reinmar** [comment]
Thanks :) We're working on this.

**Comment by mrossi-rankworks** [comment]
Can we get an ETA on this? The un official plugin can do this. Need to know when I can make the switch.
Thanks!

**Comment by kbinieda** [comment]
There is already PR with this feature waiting for approval. If nothing goes wrong it should be included in next release.
