### ISSUE TITLE
Strapi 4.4.1 - Editor not enabling after following installation instructions through Marketplace

### ISSUE THREAD

**Issue by maahtiin** [ckeditor/strapi-plugin-ckeditor#12]
After installing CKEditor through the command shared on Strapi Marketplace, as well as running `npm run build` afterwards, the plugin does not seem to be enabled after running the application.

Tested this in my current application, as well as a clean freshly installed Strapi, both 4.4.1.

Things i've tried:

- adding entry to `./config/plugins.js`:
`module.exports = () => ({
ckeditor: true
});
`
- Reinstalling and rebuilding after removing `node_modules/`, `build/` and `.cache/` folders
- Registering the plugin in the lifecycle hooks (and encountering an error that CKEditor is already registered)

**Comment by kbinieda** [comment]
You don't need to add any entry to `./config/plugins.js` if you just want to use the package. Installing package from yarn / npm should be sufficient. How do you install fresh 4.4.1 Strapi? I've used `npx create-strapi-app@4.4.1 --quickstart strapi` followed by `npm install @ckeditor/strapi-plugin-ckeditor` in Strapi dir and it seems to be working correctly.

**Comment by maahtiin** [comment]
I'll try again without adding the entry to the `plugins.js` file.
I've used the same command to install a fresh Strapi 4.4.1 instance, also followed by that same `npm install` command. Still, the default editor is shown in the admin panel.
What versions of Node/NPM do you use? Mine are 16.17.0/8.15.0.

**Comment by kbinieda** [comment]
>Still, the default editor is shown in the admin panel. 

I think we got here a slight misunderstanding how the plugin should work. This plugin won't override the default editor (for example the "rich text" field). It creates additional field, instead of the default ones.


<img width="790" alt="Screenshot 2022-10-05 at 10 17 09" src="https://user-images.githubusercontent.com/5595348/194014529-e2958a4e-360b-46e3-9b8f-78d34ec2ad84.png">

**Comment by maahtiin** [comment]
Ah thanks for showing me that! It was there all along. Sorry for not noticing, this issue can be closed 👍
