### ISSUE TITLE
Components with CKeditor fields no longer shown

### ISSUE THREAD

**Issue by edporras** [ckeditor/strapi-plugin-ckeditor#126]
Hello,

Still on strapi-4 (`4.25.12`) cause we're waiting for a bit to jump on the v5 bandwagon. If I bump `@ckeditor/strapi-plugin-ckeditor` from `0.0.13` to `0.1.0`, all components with fields using CKEditor no longer show up correctly. 

1. `4.25.12` with `0.0.13`:

![Screenshot 2024-09-26 at 13 48 35](https://github.com/user-attachments/assets/3c8532bf-28d9-4b2e-bc80-70e34e570935)

2. `4.25.12` with `0.1.0` (no other changes):

![Screenshot 2024-09-26 at 13 58 53](https://github.com/user-attachments/assets/99119885-9624-493a-b3b0-de5f71d1d99e)

I can "delete" the block with the trashcan and then re-add it but it just comes back as shown in the second picture.

Is there something else we need to update to bump to `0.1.0`?

**Comment by Mgsy** [comment]
Hi @edporras! Can you open the browser console and check if you can see any errors?

**Comment by edporras** [comment]
Hi, sorry, I was in the middle of working on a new collection and didn't get a chance to do a clean build before the weekend. I'll check on Monday as I have it all set up on my work laptop. Thanks for the quick reply.

**Comment by edporras** [comment]
@Mgsy Here you go :

```
[Error] Refused to load https://cdn.ckeditor.com/ckeditor5/43.0.0/ckeditor5.umd.js because it does not appear in the script-src directive of the Content Security Policy.
```

**Comment by edporras** [comment]
oh wow, I think we just crossed beams. I'll check that. Thanks!

**Comment by edporras** [comment]
@Mgsy yes, that was it. Sorry I missed that. Thank you.
