### ISSUE TITLE
Blank/white screen when deployed to Railway

### ISSUE THREAD

**Issue by birdzai** [ckeditor/strapi-plugin-ckeditor#141]
I've deployed a Strapi V5 app to Railway connected to a Postgres DB service.

The build and deployment logs show success, and there are no errors in any of the build, deployment or HTTP logs.

When I hit the Strapi Admin panel, I get a blank (white) screen. No build or deployment errors show up Railway logs.  I get the following error in the Javascript Console:

```bash
admin:1 Refused to load the script 'https://<host URL>/admin/strapi-xQ0AChhZ.js' because it violates the 
following Content Security Policy directive: "script-src https://cdn.ckeditor.com". 
Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```

The contents of my Strapi 5 middlewares.js file are as follows:

```js
  {
    name: "strapi::security",
    config: {
      contentSecurityPolicy: {
        useDefaults: true,
        directives: {
          "img-src": [
            "'self'",
            "data:",
            "blob:",
            "market-assets.strapi.io",
            "res.cloudinary.com",
          ],
          "media-src": [
            "'self'",
            "data:",
            "blob:",
            "market-assets.strapi.io",
            "res.cloudinary.com",
          ],
          "script-src": ["https://cdn.ckeditor.com"],
          "connect-src": [
            "'self'",
            "https:",
            "https://proxy-event.ckeditor.com",
          ],
        },
        upgradeInsecureRequests: null,
      },
    },
  },
```

My understanding is that this middlewares.js config is correct as specified in the installation docs for the CKEditor plugin.

Is that JS Console error the cause of my blank/white screen? Have I misconfigured the CKEditor plugin at all?

Note that everything works fine in DEV mode on my local machine. It's only when deployed to PRODUCTION on Railway that there is an issue. Also note that even tho I can't hit the /admin route in my browser, the Strapi REST API is working just fine in production.

### Environment

- Strapi V5.5.0
- @ckeditor/strapi-plugin-ckeditor V1.1.0

**Comment by Mgsy** [comment]
Hi! It looks like CSP rules are not applied to your production environment. Could you please confirm that your server returns `Content-Security-Policy` header with `script-src: https://cdn.ckeditor.com` directive included?

**Comment by birdzai** [comment]
You can close this. I was able to resolve the issue by inputting my custom domain as one of the CSP rules. Thanks!
