### ISSUE TITLE
Markdown output support

### ISSUE THREAD

**Issue by yusufff** [ckeditor/strapi-plugin-ckeditor#15]
The default strapi rich text output is markdown. It would be nice to preserve the output as markdown and change the editor experience.

**Comment by kbinieda** [comment]
The main idea of using CKEditor instead of built-in one is to have a html output and since it's not replacing existing field you can still use built-in editor for markdown purposes. On the other hand there is CKEditor plugin for markdown, so we might add that option in future as one of the presets.

**Comment by Mgsy** [comment]
Hi @yusufff! I've just merged PR that introduces support for Markdown output - #36.
