### ISSUE TITLE
Image size bug

### ISSUE THREAD

**Issue by eruiz-impact** [ckeditor/strapi-plugin-ckeditor#19]
When you change the position of an image to centered or side, the image renders in its original size. The formatting only applies if you have the image in line.

Environment
strapi - 4.4.5
ckeditor - 0.0.4
node - 16.18.0

**Comment by Mgsy** [comment]
Hi @eruiz-impact! I'm unable to reproduce the issue, could you please share the steps to reproduce it and the image you use? Additionally, a screencast would be helpful too.

**Comment by Mgsy** [comment]
I'm closing this issue due to a lack of activity.
