### ISSUE TITLE
How to config sourceEditing to toolbar?

### ISSUE THREAD

**Issue by WPF-ZzZz** [ckeditor/strapi-plugin-ckeditor#20]
Does anyone know how can I add the sourceEditing to the toolbar in this plugin? 

https://github.com/ckeditor/strapi-plugin-ckeditor/blob/master/admin/src/components/CKEditorInput/Configurator.js

it throws an error saying "sourceEditing" not found

https://ckeditor.com/docs/ckeditor5/latest/features/source-editing.html

If I add the custom package according to the above link, it will show duplicated plugin found in console error.

**Comment by WPF-ZzZz** [comment]
@Reinmar , do you know how we can add the sourceEditing to the existing predefined toolbar?

**Comment by axufurisamu** [comment]
I have the same question and i'm surprised it's been this long and you haven't got an answer.  It was annoying enough they changed this to a plugin instead of overriding the default WISYWIG, but they also got rid of the source button and have no good way of implementing it back in.

**Comment by Witoso** [comment]
Most likely, we missed this comment. The method for adding source editing was described here: https://github.com/ckeditor/strapi-plugin-ckeditor/issues/64#issuecomment-1594203650
