### ISSUE TITLE
H4 is not available 

### ISSUE THREAD

**Issue by denvradiy** [ckeditor/strapi-plugin-ckeditor#21]
H4 heading is not available. Also a bunch of other options are not available for use! 

These are the options of https://www.npmjs.com/package/@_sh/strapi-plugin-ckeditor 
<img width="830" alt="Screenshot 2022-11-09 at 12 20 31" src="https://user-images.githubusercontent.com/49561056/200804714-0588b04d-1d31-452a-a488-6b76129503e5.png">

And these are the options of customer field :
<img width="840" alt="Screenshot 2022-11-09 at 12 23 56" src="https://user-images.githubusercontent.com/49561056/200805498-62f7bf1b-601f-48d1-b8f0-9dfc1f68be27.png">
<img width="874" alt="Screenshot 2022-11-09 at 12 24 05" src="https://user-images.githubusercontent.com/49561056/200805528-27ce19c2-81fa-40f3-b271-40bd24a32f03.png">

A lot of functionality was removed in customer field. How can I enable all of them ?

Packages versions:
"@strapi/strapi": "4.4.7",
"@ckeditor/strapi-plugin-ckeditor": "^0.0.4",

**Comment by da-kicks-87** [comment]
I also noticed that the select dropdown's blue color doesn't match the theme color.

**Comment by Reinmar** [comment]
Released in 0.0.6.
