### ISSUE TITLE
Invariant Violation: 'maxLengthCharacters' must be prefixed with 'options.'

### ISSUE THREAD

**Issue by michalkos** [ckeditor/strapi-plugin-ckeditor#24]
After installing this plugin on Strapi v4.5.3 I get an error and blank white screen when visiting admin.

> Invariant Violation: 'maxLengthCharacters' must be prefixed with 'options.'

According to the documentation, name of the option has to start with options.

https://docs.strapi.io/developer-docs/latest/development/custom-fields.html#options

**Comment by eruiz-impact** [comment]
This needs to be addressed ASAP.

**Comment by Kazdan1994** [comment]
I have this issue to. version 4.5.2 seems to work for now

**Comment by Reinmar** [comment]
Fixed by #25 and released in 0.0.5.

**Comment by Reinmar** [comment]
Thanks for the feedback and PR! ❤️

**Comment by Kazdan1994** [comment]
Thank you for fixing this issue and happy new year
