### ISSUE TITLE
Support Node 18.x

### ISSUE THREAD

**Issue by thongbn** [ckeditor/strapi-plugin-ckeditor#26]
Hi team,
Do you any plan to support Node 18.x, it's LTS now and according to strapi document, Node v18.x is recommended for Strapi v4.3.9 and above
https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/installation/cli.html#step-1-make-sure-requirements-are-met

**Comment by aoor9** [comment]
#17

**Comment by Mgsy** [comment]
Support for Node 18 has been merged in #17, so I'm closing this issue.
