### ISSUE TITLE
Not able Install the Plugin

### ISSUE THREAD

**Issue by manishionc** [ckeditor/strapi-plugin-ckeditor#29]
After installing the plugin I am getting a Black Screen.
Please Solve this I need this to work in my sytem

**Comment by Kazdan1994** [comment]
Hey @manishionc,

Can you please add some information like your browser, which version of strapi or nodejs you use?

Thanks

**Comment by Mgsy** [comment]
I'm closing this issue due to a lack of activity. @manishionc, if you still experience the issue, please share the detailed steps to reproduce it.
