### ISSUE TITLE
Interference or "Not Supported"

### ISSUE THREAD

**Issue by fadinasr** [ckeditor/strapi-plugin-ckeditor#30]
The plugin is interfering with other components created in Strapi and causing an issue when opening a selector inside of the same component. Here's a screenshot of the issues appearing in the console:

![Screen Shot 2022-12-20 at 2 09 43 AM](https://user-images.githubusercontent.com/26388160/208551801-6c8aec6a-7ec1-45ae-9a94-6e28f142e91f.png)

```
Strapi: v4.4.4
Node: v16.13.0 
Plugin: v0.0.4
```

P.S. I tried upgrading Strapi to` v4.5.3` after the release` v0.0.5 `of the plugin and it started showing a "Not supported" placeholder with disabling the field like the screenshot below:
<img width="905" alt="Screenshot 2022-12-16 at 23 41 41 (1)" src="https://user-images.githubusercontent.com/26388160/208552262-c83bc6b7-45cc-4184-8b73-50403869a5de.png">

**Comment by Reinmar** [comment]
I tested the plugin on a fresh Strapi installation just before releasing it and all worked fine.

Could you retest this on a fresh installation?

**Comment by kuzyk** [comment]
@fadinasr that's because you added a custom field to the dynamiczone field. Custom fields not working properly in dynamiczone from strapi version 4.5.0.
try to downgrade

**Comment by fadinasr** [comment]
@kuzyk I will try to contribute to fixing this and if not, I will downgrade to a lower version

**Comment by andreaskeller** [comment]
I've had this error as well with Strapi 4.5.3, after upgrading to 4.5.5 it works again.

**Comment by Mgsy** [comment]
It seems to be an upstream issue, so I'm closing it.
