### ISSUE TITLE
Didn't work with Strapi v4.5.6

### ISSUE THREAD

**Issue by vogdb** [ckeditor/strapi-plugin-ckeditor#35]
Hi! I did
`npm install @ckeditor/strapi-plugin-ckeditor`
`npm run build`
`npm run develop`

But nothing changed in WYSIWYG editor for the field of Richtext. The same steps for the unofficial plugin worked.

Strapi project has been created with `npx create-strapi-app --quickstart strapi`.
npm version 8.19.3
node version v18.13.0

**Comment by Mgsy** [comment]
Hi @vogdb! I have just followed your steps and I was able to run CKEditor 5 without any problems. I noticed that you mention the rich text field, while CKEditor 5 was developed as a custom field, so make sure that switch to the _Custom_ tab while adding a new field:

![](https://user-images.githubusercontent.com/20988892/214240996-07de1277-be8f-4376-ac25-0099a0a76959.png)
