### ISSUE TITLE
Problem while using generalHTMLSupport & sourceEditing plugin #375

### ISSUE THREAD

**Issue by shalapatil** [ckeditor/strapi-plugin-ckeditor#64]
I am facing problem for generalHTMLSupport and sourceEditing plugin
when I add these two in plugins, I get Cannot read properties of undefined (reading 'generalHTMLSupport')

I am using custom ckeditor5 with react.

config is defined as
const CKEDITOR_BASE_CONFIG_FOR_PRESETS = { plugins: [ window.CKEditor5.autoformat.Autoformat, window.CKEditor5.basicStyles.Bold, .......... window.Ckeditor5.generalHTMLSupport.GeneralHTMLSupport,],
toolbar: {.....}`

I am following second approach (custom build) from this - https://www.thirdrocktechkno.com/blog/how-to-integrate-ckeditor5-in-strapi/
I have not imported it
because,
If I import it like following
import GeneralHtmlSupport from '@ckeditor/ckeditor5-html-support/src/generalhtmlsupport';
it gives "ckeditor-duplicated-modules error".

if I don't import then I get - "Cannot read properties of undefined (reading 'generalHTMLSupport')" error

**Comment by Witoso** [comment]
Did you fork our repo? As far as I can see, we don't offer GHS or source editing right now

You would need to:
1. Fork/Clone.
2. Add the plugins to `package.json`.
3. Add the dll's imports to https://github.com/ckeditor/strapi-plugin-ckeditor/blob/master/admin/src/components/CKEditorInput/Configurator.js
4. And then load them to the plugins list.

**Comment by shalapatil** [comment]
hey @Witoso 
Thank you so much!
This worked! 👍

**Comment by 10Life** [comment]
@shalapatil Can you let me know what exactly to be import and what exactly to be use in plugin and toolbars?

**Comment by royanon** [comment]
@shalapatil Would you mind telling me what exactly import and load in plugins list?

**Comment by royanon** [comment]
Seems like it should be 
```
      window.Ckeditor5.htmlSupport.GeneralHTMLSupport,
```

**Comment by shalapatil** [comment]
@royanon 
I think you are missing dependency in package.json
Add following to package.json:
`"@ckeditor/ckeditor5-html-support": "^38.0.1",`

Import statements:
`import ckeditor5SourceEditinDll from "@ckeditor/ckeditor5-source-editing/build/source-editing.js";
import ckeditor5GeneralHtmlSupportDll from "@ckeditor/ckeditor5-html-support/build/html-support.js";`


Add to plugins as:
`window.CKEditor5.sourceEditing.SourceEditing,
  window.CKEditor5.htmlSupport.GeneralHtmlSupport,`

Hope this will help!

**Comment by shalapatil** [comment]
@royanon You are adding `window.Ckeditor5.generalHTMLSupport.GeneralHTMLSupport` to plugins.
It should be `window.CKEditor5.htmlSupport.GeneralHtmlSupport`. Fix this and this should work.

**Comment by royanon** [comment]
@shalapatil Great! thank you! that's the problem.

**Comment by reslear** [comment]
using `https://www.npmjs.com/package/patch-package`:

[@ckeditor+strapi-plugin-ckeditor+0.0.10.patch](https://github.com/ckeditor/strapi-plugin-ckeditor/files/14146022/%40ckeditor%2Bstrapi-plugin-ckeditor%2B0.0.10.patch)

**Comment by reslear** [comment]
@mgsy please reopen issue, because patching a new version every time is a bit tedious.  any news about simple plugins configuration?
