### ISSUE TITLE
Default value

### ISSUE THREAD

**Issue by rolexta** [ckeditor/strapi-plugin-ckeditor#70]
How to add a default content value on every collection we create?

**Comment by Witoso** [comment]
To achieve that, you need to modify [the editor's config](https://github.com/ckeditor/strapi-plugin-ckeditor/blob/a30d17e8155df0e6cfd4915d09981125fd015262/admin/src/components/CKEditorInput/Configurator.js#L29) with [the `initialData` property](https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_editorconfig-EditorConfig.html#member-initialData).
