### ISSUE TITLE
Option to use target="_blank" in links + image links

### ISSUE THREAD

**Issue by kristijorgji** [ckeditor/strapi-plugin-ckeditor#72]
Hi all and congratulations for the great plugin.

I am using version
`"@ckeditor/strapi-plugin-ckeditor": "^0.0.7",`

and  would love to have more features here such as 
1. Ability to select target for the link element.
![Screenshot 2023-08-14 at 13 25 59](https://github.com/ckeditor/strapi-plugin-ckeditor/assets/15630854/273c5880-2bcc-4c99-9b47-e2ab4290ebce)

I can only enter the link now but no target
2. The same issue is also for the Media Library. If I include one image and insert link into it cannot use target
![Screenshot 2023-08-14 at 13 26 40](https://github.com/ckeditor/strapi-plugin-ckeditor/assets/15630854/c14133d4-6a94-45f4-8ee9-a5bfa047755d)

**Comment by ksyp-7** [comment]
I encountered a similar issue in one of my projects. To resolve it, I replaced "<a" with "<a target="_blank"" while parsing the HTML body on the client side, and it's now functioning perfectly.

**Comment by kristijorgji** [comment]
Thanks for the workaround @ksyp-7
That is a hack though and not adding support to the editor. You replace all <a with <a target="_blank even when you don't intend to have a new tab link!

I would like to have this option in the editor itself so we can have some links that open in new tabs other within same tab

**Comment by vr1e** [comment]
This one: https://github.com/ckeditor/strapi-plugin-ckeditor/pull/65

**Comment by kristijorgji** [comment]
@vr1e thanks for the update. I like the PR there but would be better not to have `noopener noref` as sometimes you might link internally with target _blank (new tab) and still want to trust those pages.
In that case the plugin would  be better to have option to override rel as well would be perfect to choose both target and rel manually if needed

**Comment by royanon** [comment]
I think you can pass config to the options like so
        link : {
          defaultProtocol: 'https://',
          decorators: [
            {
              mode: 'manual',
              label: 'Open in a new tab',
              attributes: {
                target: '_blank',
                rel: 'noopener noreferrer'
              }
            }
          ],
        },

**Comment by kristijorgji** [comment]
@royanon where can I use that config ?

Please provide a full example for `"@ckeditor/strapi-plugin-ckeditor": "^0.0.10",`

Thank you

**Comment by mauro-montano** [comment]
> @royanon please need more help as both the documented solution and your answer is not working for me.
> 
> I added the following config under `myStrapiApp/config/ckeditor.txt` as documented at https://market.strapi.io/plugins/@_sh-strapi-plugin-ckeditor#configuration
> 
> ```
> globalThis.CKEditorConfig = {
>     configs: {
>         markdown: {
>             editorConfig: {
>                 link: {
>                     defaultProtocol: 'https://',
>                     decorators: [
>                         {
>                             mode: 'manual',
>                             label: 'Open in a new tab',
>                             attributes: {
>                                 target: '_blank',
>                                 rel: 'noopener noreferrer'
>                             }
>                         }
>                     ],
>                 },
>             }
>         }
>     }
> }
> ```
> 
> then I do `rm -rf dist && yarn build && yarn develop` and nothing happens.
> 
> I still don't see the "Open in a new tab" in the UI.

Could you solve it? I have the same problem

**Comment by Arunjenson-ss** [comment]
any updates on this?

**Comment by tan-eson** [comment]
Thank you @royanon and @kristijorgji, I've managed to add the option to open in new tab using your method. 

For those wondering, I'm using: 
`"@ckeditor/strapi-plugin-ckeditor": "^0.0.12",`

In the following file directory: 
`node_modules/@ckeditor/strapi-plugin-ckeditor/admin/src/components/CKEditorInput/Configurator.js`

![Screenshot 2024-07-10 at 9 49 48 AM](https://github.com/ckeditor/strapi-plugin-ckeditor/assets/51318089/74bbde08-e208-4a8d-bfaa-fef3c7029199)

CKEditor config is divided into 3 presets, add the **piece of code below** in the desired presets, to allow option for opening URL in new tab for image urls. 

```
link : {
      defaultProtocol: 'https://',
      decorators: [
        {
          mode: 'manual',
          label: 'Open in a new tab',
          attributes: {
            target: '_blank',
            rel: 'noopener noreferrer'
          }
        }
      ],
    },
``` 

This is what workekd for me: 
![Screenshot 2024-07-10 at 9 53 12 AM](https://github.com/ckeditor/strapi-plugin-ckeditor/assets/51318089/7f245953-c8ed-4540-b427-df65168d388b)
