### ISSUE TITLE
Does not work with last strapi version!!! ^4.12.4

### ISSUE THREAD

**Issue by kristijorgji** [ckeditor/strapi-plugin-ckeditor#73]
"@strapi/strapi": "^4.12.4",

If you the plugin in use all those content-types won't open.

**Comment by Reinmar** [comment]
cc @ckeditor/qa-team could you take a look?

**Comment by Mgsy** [comment]
Hi @kristijorgji! Thanks for the report. However, I'm unable to reproduce your issue. For me, CKEditor 5 works properly in Strapi v4.12.4. 

Can you please share the detailed steps to reproduce the issue?

**Comment by Notaduck** [comment]
We recently migrated from v3 to v4 and tried to install the plugin today, however it does not show up in development production at all. There is no option in `custom` fields at all.

**Comment by rnatto-gempe** [comment]
> We recently migrated from v3 to v4 and tried to install the plugin today, however it does not show up in development production at all. There is no option in `custom` fields at all.
> 
> All we did was `yarn add @ckeditor/strapi-plugin-ckeditor`, `yarn build` and `yarn develop`

Here too, same problem

**Comment by Witoso** [comment]
We will reach out to strapi team to check what could be the issue. Thanks for reporting!

**Comment by kristijorgji** [comment]
@Notaduck I did not replace the original Markdown editor.

I only used this plugin as documented and as a `customField` that is all.

It was working before the Strapi upgrade and after I `yarn upgrade` strapi to the latest it is not working anymore and all the content is corrupted does not load

**Comment by Notaduck** [comment]
> @Notaduck I did not replace the original Markdown editor.
> 
> I only used this plugin as documented and as a `customField` that is all.
> 
> It was working before the Strapi upgrade and after I `yarn upgrade` strapi to the latest it is not working anymore and all the content usng it is corrupted does not load

Ok, I do not currently have the original code, but I will try to get it so I can compare a clean project with the one which upgraded from v3 -> v4.

**Comment by Mgsy** [comment]
I tried to set up a completely Strapi project (v4.5.2), then installed the CKEditor 5 custom field plugin, finally updated Strapi to 4.12.5 and rebuilt the application. After running the app, my CKEditor 5 custom field showed as expected.

Can you guys try to set up a new project and see if it works? Also, what is the error message that comes up while displaying the editor? And again - if you can find exact steps to reproduce the issue, it would be appreciated if you could post it here.

**Comment by kristijorgji** [comment]
Hi, @Mgsy how could you add Strapi 4.5.2 when strapi 4.12.x is the latest version ?

**Comment by kristijorgji** [comment]
@Mgsy it works for me as well.

To sum this up: Strapi version `^4.12.4` which I reported is buggy, but version 4.12.15 works fine and I can see your ckeditor.

I am closing the issue and again to everyone reading this, just upgrade to 4.12.5 Strapi fixed the issue there

**Comment by Witoso** [comment]
Thanks for the update @kristijorgji!

**Comment by michaelnapl** [comment]
Found this thread. Still not working for me. Installed Strapi yesterday (4.12.7), quick start setup, added CKEditor (custom field) shows as installed under plugins, not showing (as noted above) as a custom field however. Not sure what I'm missing here?
