### ISSUE TITLE
Update Engine Node

### ISSUE THREAD

**Issue by CodeDruid13** [ckeditor/strapi-plugin-ckeditor#81]
The engine "node" is incompatible with this module. Expected version ">=14.19.1 <=18.x.x". Got "20.8.0"
[2023-10-05 03:23:33] │ error Found incompatible module. 

This is in the latest Strapi 4.14.3.

It works okay for Strapi version 4.12.6

**Comment by Witoso** [comment]
AFAIK we haven't tested the editor under `20.x`; therefore there's a specific engine provided (LTS node `18.x`). We cannot just bump it, you need to align your environment.

**Comment by rlittolff-upgraal** [comment]
LTS is now Node20.
Could you please test it and bump it to Node20 ?

**Comment by marmotz** [comment]
LTS is now Node20.
Could you please test it and bump it to Node20 ?

**Comment by Witoso** [comment]
Rel: #84. @Mgsy could you take a look?

**Comment by Mgsy** [comment]
We decided to remove Node version check, as Strapi is already checking it.
