### ISSUE TITLE
Does the plugin supports media upload provider

### ISSUE THREAD

**Issue by imran-hossain03** [ckeditor/strapi-plugin-ckeditor#82]
Currently the media url returns and server upload url just like '/upload/*'.

Is there any plan to support upload provider?

**Comment by Witoso** [comment]
Could you please elaborate what do you mean by upload provider?

**Comment by imran-hossain03** [comment]
It doesn't give the full URL of the images, it just provides a relative path to the upload folder just like '/upload/*'. But the unofficial plugin works fine in this regard.

**Comment by Mgsy** [comment]
Hi @imran-hossain03! By default, Strapi Media Library API returns a relative path in the file's `url` property, however, we are using `prefixFileUrlWithBackendUrl` helper introduced by Strapi for creating the absolute path (see the code [here](https://github.com/ckeditor/strapi-plugin-ckeditor/blob/master/admin/src/components/MediaLib/index.js#L12)).  

The helper relies on `window.strapi.backendURL`, so make sure that you have it configured properly.
