### ISSUE TITLE
Failed to install with current node LTS version: 20.9.0

### ISSUE THREAD

**Issue by 101sam** [ckeditor/strapi-plugin-ckeditor#86]
The current [LTS version is 20.9.0 ](https://nodejs.org/en)

This module is broken on all our servers using strapi 

```
error @ckeditor/strapi-plugin-ckeditor@0.0.9: The engine "node" is incompatible with this module. Expected version ">=14.19.1 <=18.x.x". Got "20.9.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

## Recreate issue:
Install the latest LTS node: 
Upgrade to the latest strapi:  4.15.0

`yarn install `or `npm install`

**Comment by Witoso** [comment]
Duplicate: #81
