### ISSUE TITLE
How to customize the configuration？

### ISSUE THREAD

**Issue by 523299338** [ckeditor/strapi-plugin-ckeditor#88]
How to customize the configuration or options when use as CKEditor 5 custom field

eg: 
I want to add the function of the color picker, 
but besides modifying the node_modules, I don't know if there are any other ways to add custom configurations?

**Comment by Hoax017** [comment]
you cant without fork

**Comment by Witoso** [comment]
Exactly, you need to clone the repo, and configure the options/plugins as you like.

**Comment by royanon** [comment]
I am going to use patch-package instead of clone the whole things for the moment before options support. However, where is the options?

**Comment by royanon** [comment]
I put that in /admin/src/components/CKEditorInput/Configurator.js, it's working, but not so sure. Hope the options config will be support asap.

**Comment by Mgsy** [comment]
Thanks for your feedback! Actually, we have this feature request already reported (#34), so I'm closing this one as a duplicate. For now, you can clone the plugin repository and adjust the configuration directly in the source code.
