### ISSUE TITLE
Markdown output not working

### ISSUE THREAD

**Issue by stevennt** [ckeditor/strapi-plugin-ckeditor#90]
The plugin doesn't output Markdown in my setup. Few screenshots can be found below. Anyone having the same issue?

<img width="811" alt="image" src="https://github.com/ckeditor/strapi-plugin-ckeditor/assets/32351181/6f500604-9b34-4dfa-819d-4e56bbbcbefb">

<img width="641" alt="image" src="https://github.com/ckeditor/strapi-plugin-ckeditor/assets/32351181/6961f3ab-5024-4b91-9d5e-d992bd31c384">

<img width="847" alt="image" src="https://github.com/ckeditor/strapi-plugin-ckeditor/assets/32351181/9b59d293-e9b2-47a6-a59f-68a45175bc9a">

STRAPI VERSION v4.10.4
NODE VERSION v18.16.1

**Comment by Mgsy** [comment]
Hi @stevennt! The output on your screenshot shows valid markdown, only the table is represented as HTML (note that HTML is also a valid markdown). As markdown is very simple, it doesn't support advanced styling like table styles, so the representation needs to be in HTML to avoid data/styling loss. The same output you can observe in our demo - https://ckeditor.com/docs/ckeditor5/latest/features/markdown.html#demo. 

We are using external library for markdown <--> HTML conversion, so this is the way it handles the data.

**Comment by SuperCipher** [comment]
So there is no option to create a table using GUI and have the source be the markdown? e.g.
`| Inline formatting | Shortcut |
| --- | --- |
| **Bold** | Type `**` or `__` around your text. |
| _Italic_ | Type `*` or `_` around your text. |
| `Code` | Type `ˋ` around your text. |
| ~Strikethrough~ | Type `~~` around your text. |`
