### ISSUE TITLE
Add new fonts

### ISSUE THREAD

**Issue by colonder** [ckeditor/strapi-plugin-ckeditor#93]
How do I add new font families to the editor?

**Comment by colonder** [comment]
At this point I think far better CKEditor integration is this one https://github.com/nshenderov/strapi-plugin-ckeditor

**Comment by girish-soman** [comment]
> At this point I think far better CKEditor integration is this one https://github.com/nshenderov/strapi-plugin-ckeditor

Hi @colonder did you manage to add custom font families in this plugin?

**Comment by colonder** [comment]
In this one, no. In the one that I linked, yes.

**Comment by girish-soman** [comment]
> In this one, no. In the one that I linked, yes.

@colonder Could you help me to understand how you have managed to add the custom font families in this https://github.com/nshenderov/strapi-plugin-ckeditor

**Comment by colonder** [comment]
Create a discussion thread in https://github.com/nshenderov/strapi-plugin-ckeditor/discussions

**Comment by girish-soman** [comment]
> Create a discussion thread in https://github.com/nshenderov/strapi-plugin-ckeditor/discussions
Yes I have created a discussion thread
