### ISSUE TITLE
AI assistant feature?

### ISSUE THREAD

**Issue by Jeff-Tian** [ckeditor/strapi-plugin-ckeditor#94]
How to enable AI feature in strapi's ckeditor?

**Comment by Mgsy** [comment]
Hi! Currently, there is no possibility to manage plugins from the custom field configuration form. However, if you want to add a plugin, you need to fork the repository and add the plugin to the [editor configuration](https://github.com/ckeditor/strapi-plugin-ckeditor/blob/master/admin/src/components/CKEditorInput/Configurator.js). You can read more about installing plugins [in the documentation](https://ckeditor.com/docs/ckeditor5/latest/installation/plugins/installing-plugins.html).
